[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "criterion"
harness = false
